# 测试配置文件
# 
# 
server:
  port: 8801
spring:
  # 数据库配置
  # todo 需替换配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://114.55.61.179/zoubi
    username: root
    password: Tt98.0512
  # Redis 配置
  # todo 需替换配置
  redis:
    redisson:
      file: classpath:redisson-test.yml